import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
const moduleName=process.env.ARTIFACT_TOOL_PATH?pathToFileURL(process.env.ARTIFACT_TOOL_PATH).href:"@oai/artifact-tool";
const {Presentation,PresentationFile}=await import(moduleName);
const [specPath,projectPath,mapPath,outputPath,renderDir]=process.argv.slice(2);if(!renderDir)throw new Error("usage: build_design_statement SPEC PROJECT MAP OUTPUT RENDERS");
const spec=JSON.parse(await fs.readFile(specPath,"utf8")),project=JSON.parse(await fs.readFile(projectPath,"utf8")),assets=JSON.parse(await fs.readFile(mapPath,"utf8"));if(spec.approvalStatus!=="approved")throw new Error("approved design statement required");
const W=spec.profile==="live"?1280:1190.55,H=spec.profile==="live"?720:841.89,C={paper:"#F6F2E8",ink:"#141512",muted:"#65665F",line:"#CBC6BA",rust:"#BA4B27",white:"#FFFFFF",dark:"#181916"},FONT="Malgun Gothic";
const deck=Presentation.create({slideSize:{width:W,height:H}});const blob=async p=>new Uint8Array(await fs.readFile(p));const save=async(p,b)=>{await fs.mkdir(path.dirname(p),{recursive:true});await fs.writeFile(p,new Uint8Array(await b.arrayBuffer()));};
function text(slide,name,value,pos,style={}){const box=slide.shapes.add({geometry:"textbox",name,position:pos,fill:"none",line:{style:"solid",fill:"none",width:0}});box.text=String(value??"");box.text.style={typeface:FONT,fontSize:18,color:C.ink,verticalAlignment:"top",autoFit:"shrinkText",...style};return box;}
function rule(slide,name,x,y,w,color=C.line,weight=1){slide.shapes.add({geometry:"straightConnector1",name,position:{left:x,top:y,width:w,height:0},fill:"none",line:{style:"solid",fill:color,width:weight}});}
async function visual(slide,slot,pos){const source=assets[slot.elementId];if(!source)return false;slide.images.add({blob:await blob(source.path),contentType:source.contentType||"image/png",alt:"Approved architectural evidence",fit:slot.fit==="cover"?"cover":"contain",position:pos});return true;}
function chrome(slide,page){text(slide,`index-${page.number}`,String(page.number).padStart(2,"0"),{left:34,top:35,width:45,height:18},{fontSize:10,bold:true,color:C.rust});text(slide,`section-${page.number}`,page.sectionTitle,{left:80,top:35,width:W-125,height:18},{fontSize:9,bold:true,color:C.muted,letterSpacing:1});rule(slide,`head-${page.number}`,80,67,W-115);rule(slide,`foot-${page.number}`,80,H-54,W-115);text(slide,`project-${page.number}`,project.name,{left:80,top:H-42,width:520,height:16},{fontSize:8,color:C.muted});text(slide,`folio-${page.number}`,`${String(page.number).padStart(2,"0")} / ${String(spec.pages.length).padStart(2,"0")}`,{left:W-170,top:H-42,width:135,height:16},{fontSize:8,color:C.muted,alignment:"right"});}
for(const page of spec.pages){const slide=deck.slides.add();slide.background.fill=page.pageType==="final_synthesis"?C.dark:C.paper;const slots=page.visualSlots||[];
 if(page.pageType==="cover"){if(slots[0])await visual(slide,slots[0],{left:W*.52,top:0,width:W*.48,height:H});text(slide,"cover-kicker","ARCHITECTURE DESIGN STATEMENT",{left:62,top:62,width:W*.42,height:22},{fontSize:10,bold:true,color:C.rust,letterSpacing:1.5});text(slide,"cover-title",page.title,{left:62,top:150,width:W*.39,height:145},{fontSize:44,bold:true});rule(slide,"cover-rule",62,330,160,C.rust,3);text(slide,"cover-claim",page.claim,{left:62,top:370,width:W*.39,height:140},{fontSize:20,bold:true});}
 else if(page.pageType==="final_synthesis"){if(slots[0])await visual(slide,slots[0],{left:W*.58,top:0,width:W*.42,height:H});text(slide,"closing-kicker","FINAL SYNTHESIS",{left:62,top:70,width:480,height:22},{fontSize:10,bold:true,color:C.rust,letterSpacing:1.5});text(slide,"closing-title",page.title,{left:62,top:155,width:W*.47,height:100},{fontSize:38,bold:true,color:C.white});rule(slide,"closing-rule",62,300,160,C.rust,3);text(slide,"closing-claim",page.claim,{left:62,top:340,width:W*.46,height:180},{fontSize:20,bold:true,color:C.white});}
 else{chrome(slide,page);text(slide,`title-${page.number}`,page.title,{left:80,top:88,width:W-120,height:54},{fontSize:28,bold:true});const technical=["full_plan","context_map","section_elevation"].includes(page.pageType),hero=page.pageType==="hero_render";
  if(hero&&slots[0]){await visual(slide,slots[0],{left:80,top:165,width:W-115,height:H-260});text(slide,`hero-claim-${page.number}`,page.claim,{left:80,top:H-84,width:W-230,height:28},{fontSize:16,bold:true});}
  else if(technical&&slots[0]){await visual(slide,slots[0],{left:80,top:160,width:W-115,height:H-250});text(slide,`tech-claim-${page.number}`,page.claim,{left:80,top:H-85,width:W-150,height:30},{fontSize:14,bold:true});}
  else{const left=80,leftW=W*.37;text(slide,`claim-${page.number}`,page.claim,{left,top:175,width:leftW,height:130},{fontSize:19,bold:true});if(page.supportingText)text(slide,`body-${page.number}`,page.supportingText,{left,top:335,width:leftW,height:210},{fontSize:11,color:C.muted});if(slots.length===1)await visual(slide,slots[0],{left:W*.48,top:165,width:W*.48-35,height:H-250});else for(const [index,slot] of slots.slice(0,4).entries()){const cols=2,gap=14,cellW=(W*.48-49-gap)/cols,cellH=(H-265-gap)/2;await visual(slide,slot,{left:W*.48+(index%2)*(cellW+gap),top:165+Math.floor(index/2)*(cellH+gap),width:cellW,height:cellH});}}
 }
 slide.speakerNotes.textFrame.setText(page.notes);slide.speakerNotes.setVisible(true);
}
await fs.mkdir(renderDir,{recursive:true});for(const [index,slide] of deck.slides.items.entries()){const stem=`slide-${String(index+1).padStart(2,"0")}`;await save(path.join(renderDir,`${stem}.png`),await deck.export({slide,format:"png",scale:1}));await fs.writeFile(path.join(renderDir,`${stem}.layout.json`),await(await slide.export({format:"layout"})).text(),"utf8");}await save(path.join(renderDir,"montage.webp"),await deck.export({format:"webp",montage:true,scale:1}));await(await PresentationFile.exportPptx(deck)).save(outputPath);console.log(JSON.stringify({outputPath,pageCount:deck.slides.items.length}));
