import { useMemo, useState } from "react";
import { Check, ChevronDown, ChevronUp, Copy, FileOutput, Trash2 } from "lucide-react";
import { db } from "./db";
import { downloadFromEndpoint, safeName } from "./projectIO";
import { makeDesignStatement, validateDesignStatement } from "./smartApi";
import { useStudio } from "./store";
import type { DesignStatementPageV1, DesignStatementSpecV1 } from "./types";
import { newId } from "./types";

const PAGE_TYPES:DesignStatementPageV1["pageType"][]=["cover","contents","hero_render","summary_axon","context_map","problem_evidence","concept_statement","process_sequence","program_mapping","full_plan","plan_callout","section_elevation","material_detail","gallery","final_synthesis"];

export function DesignStatementPanel({setNotice}:{setNotice:(value:string)=>void}){
 const state=useStudio(),project=state.project!;const [profile,setProfile]=useState<"detailed"|"live">("detailed"),[target,setTarget]=useState(24),[audience,setAudience]=useState("건축 설계 교수·심사위원"),[spec,setSpec]=useState<DesignStatementSpecV1|undefined>(project.designStatementSpecs.at(-1)),[busy,setBusy]=useState(false);
 const review=useMemo(()=>spec?.pages.reduce((sum,page)=>sum+page.reviewFlags.length,0)??0,[spec]);
 const persist=(next:DesignStatementSpecV1)=>{setSpec(next);state.commit(draft=>{const index=draft.designStatementSpecs.findIndex(item=>item.id===next.id);if(index>=0)draft.designStatementSpecs[index]=next;else draft.designStatementSpecs.push(next);});void db.designStatementSpecs.put(next);};
 const generate=async()=>{setBusy(true);try{const next=await makeDesignStatement(project,profile,target,audience);persist(next);setNotice(`${next.pageCount}쪽 근거 기반 설계설명서 초안을 만들었습니다.`);}catch(error){setNotice(error instanceof Error?error.message:String(error));}finally{setBusy(false);}};
 const edit=(id:string,patch:Partial<DesignStatementPageV1>)=>{if(spec)persist({...spec,approvalStatus:"draft",updatedAt:new Date().toISOString(),pages:spec.pages.map(page=>page.id===id?{...page,...patch,approvalStatus:"draft"}:page)});};
 const reorder=(id:string,delta:number)=>{if(!spec)return;const pages=[...spec.pages],index=pages.findIndex(page=>page.id===id),next=Math.max(0,Math.min(pages.length-1,index+delta));if(index===next)return;const [item]=pages.splice(index,1);pages.splice(next,0,item);persist({...spec,approvalStatus:"draft",pages:pages.map((page,i)=>({...page,number:i+1})),updatedAt:new Date().toISOString()});};
 const duplicate=(page:DesignStatementPageV1)=>{if(!spec)return;const index=spec.pages.findIndex(item=>item.id===page.id),pages=[...spec.pages];pages.splice(index+1,0,{...structuredClone(page),id:newId(),approvalStatus:"draft"});persist({...spec,approvalStatus:"draft",pageCount:pages.length,pages:pages.map((item,i)=>({...item,number:i+1})),updatedAt:new Date().toISOString()});};
 const remove=(id:string)=>{if(!spec||spec.pages.length<=1)return;const pages=spec.pages.filter(page=>page.id!==id).map((page,i)=>({...page,number:i+1}));persist({...spec,approvalStatus:"draft",pageCount:pages.length,pages,updatedAt:new Date().toISOString()});};
 const approve=async()=>{if(!spec)return;setBusy(true);try{const result=await validateDesignStatement(project,spec);if(!result.valid){setNotice(`승인 차단: ${result.errors.join(" / ")}`);return;}persist({...spec,approvalStatus:"approved",updatedAt:new Date().toISOString()});setNotice(result.warnings.length?`승인됨 · ${result.warnings.join(" / ")}`:"설계설명서를 승인했습니다.");}finally{setBusy(false);}};
 const output=async(kind:"pptx"|"pdf")=>{if(!spec||spec.approvalStatus!=="approved")return;setBusy(true);try{await downloadFromEndpoint(project,`/api/presentation/design-statement/export-${kind}`,`${safeName(project.name)}-설계설명서.${kind}`,{designStatementSpecId:spec.id});setNotice(`A3 설계설명서 ${kind.toUpperCase()}를 생성했습니다.`);}catch(error){setNotice(error instanceof Error?error.message:String(error));}finally{setBusy(false);}};
 return <><div className="smart-hero"><FileOutput size={20}/><div><b>A3 설계설명서</b><span>승인 근거 → 적응형 페이지 → PPTX + RGB PDF</span></div></div><div className="statement-profile"><button className={profile==="detailed"?"active":""} onClick={()=>{setProfile("detailed");setTarget(24)}}>A3 Detailed</button><button className={profile==="live"?"active":""} onClick={()=>{setProfile("live");setTarget(16)}}>16:9 Live</button></div><div className="story-settings"><label>청중<input value={audience} onChange={e=>setAudience(e.target.value)}/></label><label>목표 쪽<input type="number" min={profile==="detailed"?18:14} max={profile==="detailed"?30:18} value={target} onChange={e=>setTarget(Number(e.target.value))}/></label></div><button className="primary full-action" disabled={busy||!project.contentBlocks.some(item=>item.status==="approved")} onClick={()=>void generate()}>{busy?"구성 중…":"근거 기반 초안 생성"}</button>{spec&&<><div className="story-summary"><b>{spec.pageCount}쪽 · {spec.profile}</b><span>검토 플래그 {review}</span></div><div className="statement-pages">{spec.pages.map(page=><article key={page.id}><div className="statement-thumb"><b>{String(page.number).padStart(2,"0")}</b><span>{page.sectionTitle}</span><em>{page.pageType}</em></div><div className="statement-fields"><input value={page.title} aria-label={`${page.number}쪽 제목`} onChange={e=>edit(page.id,{title:e.target.value})}/><textarea value={page.claim} aria-label={`${page.number}쪽 주장`} onChange={e=>edit(page.id,{claim:e.target.value})}/><textarea value={page.supportingText} aria-label={`${page.number}쪽 설명`} onChange={e=>edit(page.id,{supportingText:e.target.value})}/><select value={page.pageType} onChange={e=>edit(page.id,{pageType:e.target.value as DesignStatementPageV1["pageType"]})}>{PAGE_TYPES.map(value=><option key={value}>{value}</option>)}</select><small>{page.sourceContentBlockIds.length} BLOCK · {page.sourceElementIds.length} ELEMENT{page.reviewFlags.length?` · ${page.reviewFlags.join(" / ")}`:""}</small></div><div className="statement-page-actions"><button title="앞으로" onClick={()=>reorder(page.id,-1)}><ChevronUp size={12}/></button><button title="뒤로" onClick={()=>reorder(page.id,1)}><ChevronDown size={12}/></button><button title="복제" onClick={()=>duplicate(page)}><Copy size={12}/></button><button title="삭제" onClick={()=>remove(page.id)}><Trash2 size={12}/></button></div></article>)}</div><div className="story-actions"><button className={spec.approvalStatus==="approved"?"approved":""} disabled={busy} onClick={()=>void approve()}><Check size={13}/>{spec.approvalStatus==="approved"?"승인됨":"검토 완료 · 승인"}</button><button className="primary" disabled={busy||spec.approvalStatus!=="approved"} onClick={()=>void output("pptx")}>PPTX</button><button className="primary" disabled={busy||spec.approvalStatus!=="approved"} onClick={()=>void output("pdf")}>PDF</button></div></>}</>;
}
