import { useMemo, useState } from "react";
import { FileStack, ShieldCheck, X } from "lucide-react";
import { db } from "./db";
import { useStudio } from "./store";
import type { AssetRef, PanelElement, PsdLayerRefV1, PsdSourceRefV1 } from "./types";
import { DEFAULT_ADJUSTMENTS, DEFAULT_MASK, DEFAULT_TRANSFORM, newId } from "./types";

type Inspection = { source:{assetId:string;sha256:string;name:string;sizeBytes:number};format:"PSD"|"PSB";widthPx:number;heightPx:number;dpi:number;bitDepth:8|16;colorMode:"RGB";layerCount:number;layers:PsdLayerRefV1[];compositePreviewUrl:string;reviewStatus:"manual_verification_required" };

export async function uploadPsd(file:File,onProgress:(value:number)=>void):Promise<Inspection>{
  const start=await fetch("/api/uploads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:file.name,sizeBytes:file.size})});if(!start.ok)throw new Error((await start.json()).detail??"업로드 세션 생성 실패");
  const session=await start.json() as {sessionId:string;chunkSize:number;chunkCount:number};
  for(let index=0;index<session.chunkCount;index++){const bytes=await file.slice(index*session.chunkSize,Math.min(file.size,(index+1)*session.chunkSize)).arrayBuffer();const hash=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))).map(v=>v.toString(16).padStart(2,"0")).join("");const response=await fetch(`/api/uploads/${session.sessionId}/chunks/${index}`,{method:"PUT",headers:{"X-Chunk-SHA256":hash},body:bytes});if(!response.ok)throw new Error((await response.json()).detail??"청크 업로드 실패");onProgress(Math.round((index+1)/session.chunkCount*80));}
  const done=await fetch(`/api/uploads/${session.sessionId}/complete`,{method:"POST"});if(!done.ok)throw new Error((await done.json()).detail??"원본 확정 실패");const source=await done.json() as {assetId:string};
  const inspect=await fetch("/api/psd/inspect",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assetId:source.assetId})});if(!inspect.ok)throw new Error((await inspect.json()).detail??"PSD 분석 실패");onProgress(100);return inspect.json();
}

export function PsdImportModal({file,onClose,setNotice}:{file:File;onClose:()=>void;setNotice:(value:string)=>void}){
  const state=useStudio(),project=state.project!,board=project.boards.find(b=>b.id===state.activeBoardId)!;const [inspection,setInspection]=useState<Inspection>();const [selected,setSelected]=useState<string[]>([]);const [progress,setProgress]=useState(0);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const layers=useMemo(()=>inspection?.layers.filter(layer=>layer.kind!=="group"&&layer.visible)??[],[inspection]);
  const inspect=async()=>{setBusy(true);setError("");try{const result=await uploadPsd(file,setProgress);setInspection(result);setSelected(result.layers.filter(layer=>layer.kind!=="group"&&layer.visible).map(layer=>layer.id));}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setBusy(false);}};
  const apply=async()=>{if(!inspection)return;setBusy(true);try{const sourceId=newId(),elementIds:string[]=[];const merged=await fetch(inspection.compositePreviewUrl).then(r=>r.blob()),mergedId=newId();await db.assets.put({id:mergedId,projectId:project.id,blob:merged,thumbnail:merged,updatedAt:new Date().toISOString()});const assets:AssetRef[]=[{id:mergedId,name:`${file.name} · merged reference`,mime:"image/webp",sizeBytes:merged.size,widthPx:inspection.widthPx,heightPx:inspection.heightPx,review:["잠긴 PSD 합성 대조 배경"]}];const common={boardId:board.id,rotationDeg:0,visible:true,transform:structuredClone(DEFAULT_TRANSFORM)};const background:PanelElement={...common,id:newId(),name:`PSD 대조 · ${file.name}`,xMm:0,yMm:0,widthMm:board.widthMm,heightMm:board.heightMm,opacity:.24,locked:true,type:"image",assetId:mergedId,cropNormalized:{x:0,y:0,w:1,h:1},fit:"contain",mask:structuredClone(DEFAULT_MASK),adjustments:structuredClone(DEFAULT_ADJUSTMENTS)};const elements:PanelElement[]=[background];elementIds.push(background.id);const scale=Math.min(board.widthMm/inspection.widthPx,board.heightMm/inspection.heightPx),ox=(board.widthMm-inspection.widthPx*scale)/2,oy=(board.heightMm-inspection.heightPx*scale)/2;
    for(const layer of layers.filter(item=>selected.includes(item.id))){const response=await fetch(`/api/psd/assets/${inspection.source.assetId}/layers/${encodeURIComponent(layer.id)}/preview`);if(!response.ok)throw new Error(`${layer.path} 미리보기 실패`);const blob=await response.blob(),assetId=newId();await db.assets.put({id:assetId,projectId:project.id,blob,thumbnail:blob,updatedAt:new Date().toISOString()});assets.push({id:assetId,name:layer.path,mime:"image/png",sizeBytes:blob.size,review:layer.reviewFlags});const [left,top,right,bottom]=layer.bboxPx;const element:PanelElement={...common,id:newId(),name:layer.name,xMm:ox+left*scale,yMm:oy+top*scale,widthMm:Math.max(1,(right-left)*scale),heightMm:Math.max(1,(bottom-top)*scale),opacity:layer.opacity,locked:layer.locked,type:"psd_layer",sourceId,layerId:layer.id,previewAssetId:assetId,renderPolicy:layer.compatibility==="raster_render_unit"?"composite-unit":"source-layer",cropNormalized:{x:0,y:0,w:1,h:1},fit:"contain",mask:structuredClone(DEFAULT_MASK),adjustments:structuredClone(DEFAULT_ADJUSTMENTS),provenance:{sourceSha256:inspection.source.sha256,layerPath:layer.path,fingerprint:layer.fingerprint},reviewFlags:layer.reviewFlags};elements.push(element);elementIds.push(element.id);}
    const source:PsdSourceRefV1={id:sourceId,assetId:inspection.source.assetId,sha256:inspection.source.sha256,name:inspection.source.name,format:inspection.format,widthPx:inspection.widthPx,heightPx:inspection.heightPx,dpi:inspection.dpi,colorMode:inspection.colorMode,bitDepth:inspection.bitDepth,layers:inspection.layers,storageMode:"linked",reviewStatus:inspection.reviewStatus,elementIds,importedAt:new Date().toISOString()};state.commit(draft=>{draft.assets.push(...assets);draft.elements.push(...elements);draft.boards.find(item=>item.id===board.id)!.elementIds.push(...elements.map(item=>item.id));draft.psdSources.push(source);});state.setSelection(elements.length>1?[elements[1].id]:[background.id]);setNotice(`${inspection.format} ${selected.length}개 레이어를 원본 연결 상태로 가져왔습니다.`);onClose();}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setBusy(false);}};
  return <div className="modal-backdrop"><section className="modal psd-import-modal"><header><div><small>STUDIO 1.4 · LINKED SOURCE</small><h2>PSD / PSB 레이어 가져오기</h2></div><button onClick={onClose}><X size={18}/></button></header>{!inspection?<div className="psd-intro"><FileStack size={34}/><strong>{file.name}</strong><span>{(file.size/1024/1024).toFixed(1)} MB · 32MB 청크</span><p>원본은 불변 저장하고 합성본과 레이어 미리보기만 캔버스에 올립니다.</p><button className="primary" disabled={busy} onClick={()=>void inspect()}>{busy?`업로드·분석 ${progress}%`:"원본 검사 시작"}</button></div>:<><div className="psd-summary"><b>{inspection.format} · {inspection.widthPx}×{inspection.heightPx}px</b><span>{inspection.bitDepth}bit RGB · {inspection.layerCount} layers</span><em>{inspection.reviewStatus}</em></div><div className="psd-layer-list"><label className="psd-select-all"><input type="checkbox" checked={selected.length===layers.length} onChange={e=>setSelected(e.target.checked?layers.map(item=>item.id):[])}/><b>표시 레이어 전체 선택</b></label>{inspection.layers.map(layer=><label key={layer.id} className={`psd-layer-row status-${layer.compatibility}`}><input type="checkbox" disabled={layer.kind==="group"} checked={selected.includes(layer.id)} onChange={e=>setSelected(e.target.checked?[...selected,layer.id]:selected.filter(id=>id!==layer.id))}/><span><b>{layer.path}</b><small>{layer.kind} · {layer.compatibility}</small></span><ShieldCheck size={14}/></label>)}</div><footer><span>{selected.length}개 + 합성 대조 배경</span><button onClick={onClose}>취소</button><button className="primary" disabled={busy||!selected.length} onClick={()=>void apply()}>{busy?"연결 중…":"선택 레이어 가져오기"}</button></footer></>}{error&&<p className="error-line">{error}</p>}</section></div>;
}

type RelinkMatch={oldLayerId:string|null;newLayerId:string|null;status:"same"|"modified"|"added"|"missing"|"ambiguous";confidence:number};
export function PsdRelinkModal({file,sourceId,onClose,setNotice}:{file:File;sourceId:string;onClose:()=>void;setNotice:(value:string)=>void}){
 const state=useStudio(),project=state.project!,source=project.psdSources.find(item=>item.id===sourceId)!;const[inspection,setInspection]=useState<Inspection>(),[matches,setMatches]=useState<RelinkMatch[]>([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState(""),[approved,setApproved]=useState(false);
 const compare=async()=>{setBusy(true);try{const next=await uploadPsd(file,setProgress);const response=await fetch("/api/psd/relink/compare",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({oldLayers:source.layers,newAssetId:next.source.assetId})});if(!response.ok)throw new Error((await response.json()).detail??"재연결 비교 실패");const result=await response.json() as {matches:RelinkMatch[]};setInspection(next);setMatches(result.matches);}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setBusy(false);}};
 const apply=async()=>{if(!inspection||!approved)return;setBusy(true);try{const response=await fetch("/api/psd/relink/apply",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({approved:true,matches})});if(!response.ok)throw new Error((await response.json()).detail??"재연결 적용 실패");const byOld=new Map(matches.filter(item=>item.oldLayerId).map(item=>[item.oldLayerId!,item]));for(const element of project.elements){if(element.type!=="psd_layer"||element.sourceId!==sourceId)continue;const match=byOld.get(element.layerId);if(match?.newLayerId){const blob=await fetch(`/api/psd/assets/${inspection.source.assetId}/layers/${encodeURIComponent(match.newLayerId)}/preview`).then(r=>r.blob());await db.assets.update(element.previewAssetId,{blob,thumbnail:blob,updatedAt:new Date().toISOString()});}}
   state.commit(draft=>{const target=draft.psdSources.find(item=>item.id===sourceId)!;target.assetId=inspection.source.assetId;target.sha256=inspection.source.sha256;target.name=inspection.source.name;target.layers=inspection.layers;target.reviewStatus="manual_verification_required";for(const element of draft.elements){if(element.type!=="psd_layer"||element.sourceId!==sourceId)continue;const match=byOld.get(element.layerId);if(match?.newLayerId){const layer=inspection.layers.find(item=>item.id===match.newLayerId);element.layerId=match.newLayerId;if(layer){element.provenance={sourceSha256:inspection.source.sha256,layerPath:layer.path,fingerprint:layer.fingerprint};element.reviewFlags=layer.reviewFlags;}}else if(match?.status==="missing")element.reviewFlags=[...element.reviewFlags,"재연결 원본에서 누락 · 자동 삭제하지 않음"];}});setNotice("PSD 재연결을 단일 이력으로 적용했습니다. 좌표·crop·변형은 유지했습니다.");onClose();}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setBusy(false);}};
 const count=(status:RelinkMatch["status"])=>matches.filter(item=>item.status===status).length;
 return <div className="modal-backdrop"><section className="modal psd-import-modal"><header><div><small>PSD RELINK · PRESERVE TRANSFORMS</small><h2>{source.name} 재연결</h2></div><button onClick={onClose}><X size={18}/></button></header>{!inspection?<div className="psd-intro"><FileStack size={34}/><strong>{file.name}</strong><span>{progress}% · SHA-256 비교</span><p>내부 ID를 우선 비교하고, 실패하면 경로·종류·bbox fingerprint를 사용합니다. 누락 레이어는 삭제하지 않습니다.</p><button className="primary" disabled={busy} onClick={()=>void compare()}>{busy?"분석 중…":"새 원본 비교"}</button></div>:<><div className="psd-summary"><b>동일 {count("same")} · 수정 {count("modified")}</b><span>추가 {count("added")} · 누락 {count("missing")}</span><em>manual_verification_required</em></div><div className="psd-layer-list">{matches.map((match,index)=><div className="psd-layer-row" key={`${match.oldLayerId}-${match.newLayerId}-${index}`}><span>{String(index+1).padStart(2,"0")}</span><span><b>{match.oldLayerId??"새 레이어"} → {match.newLayerId??"누락"}</b><small>{match.status} · confidence {Math.round(match.confidence*100)}%</small></span><ShieldCheck size={14}/></div>)}</div><label className="review-check"><input type="checkbox" checked={approved} onChange={event=>setApproved(event.target.checked)}/><span>대응 관계를 검토했고, 누락 레이어를 자동 삭제하지 않는 재연결을 승인합니다.</span></label><footer><button onClick={onClose}>취소</button><button className="primary" disabled={!approved||busy} onClick={()=>void apply()}>재연결 적용</button></footer></>}{error&&<p className="error-line">{error}</p>}</section></div>;
}
