import { useEffect, useMemo, useRef, useState } from "react";
import { Check, FileStack, Grid3X3, Plus, Presentation, Sparkles, Upload } from "lucide-react";
import { db } from "./db";
import { applyTypographyRole, readabilityWarnings } from "./readability";
import { recommendLayouts, makeStoryboard, suggestBlocks, validateProposal } from "./smartApi";
import { useStudio } from "./store";
import type { ContentLabel, LayoutProposalV1, ReferenceLayoutV1, StudioPresentationSpecV1, TypographyRole } from "./types";
import { BOARD_PRESETS, CONTENT_LABELS, derivedPixels, newId } from "./types";
import { downloadFromEndpoint, safeName } from "./projectIO";

const LABEL_KO: Record<string, string> = { title: "제목", project_info: "프로젝트 정보", prologue: "프롤로그", context: "맥락", site_analysis: "대지 분석", concept: "개념", design_process: "설계 과정", massing: "매싱", program: "프로그램", master_plan: "배치", site_plan: "사이트 플랜", floor_plan: "평면", plan: "도면", circulation: "동선", section: "단면", elevation: "입면", facade: "파사드", diagram: "다이어그램", render: "렌더", detail: "상세", materials: "재료", accessibility: "접근성", performance: "성능", caption: "캡션", source: "출처", colophon: "콜로폰" };

export function DocumentSettingsModal({ onClose }: { onClose: () => void }) {
  const state = useStudio(); const board = state.project?.boards.find((item) => item.id === state.activeBoardId);
  const [width, setWidth] = useState(board?.widthMm ?? 841); const [height, setHeight] = useState(board?.heightMm ?? 1189);
  const [dpi, setDpi] = useState(board?.printProfile.targetDpi ?? 300); const [bleed, setBleed] = useState(board?.bleedMm ?? 3); const [safe, setSafe] = useState(board?.safeMarginMm ?? 10);
  const [viewing, setViewing] = useState(board?.printProfile.viewingDistanceMm ?? 1200); const [mode, setMode] = useState<"scale" | "keep" | "duplicate">("keep"); const [lockRatio, setLockRatio] = useState(true);
  if (!board) return null;
  const widthPx = derivedPixels(width, dpi); const heightPx = derivedPixels(height, dpi); const pixels = widthPx * heightPx; const memoryGb = pixels * 4 / 1024 ** 3;
  const setWidthSafe = (value: number) => { if (lockRatio) setHeight(Math.round(value / board.widthMm * board.heightMm * 10) / 10); setWidth(value); };
  const setHeightSafe = (value: number) => { if (lockRatio) setWidth(Math.round(value / board.heightMm * board.widthMm * 10) / 10); setHeight(value); };
  const apply = () => { state.resizeBoard(board.id, width, height, mode, dpi); const active = useStudio.getState().activeBoardId; state.commit((draft) => { const target = draft.boards.find((item) => item.id === active); if (target) { target.bleedMm = bleed; target.safeMarginMm = safe; target.printProfile.viewingDistanceMm = viewing; } }); onClose(); };
  return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal document-modal" onMouseDown={(event) => event.stopPropagation()}><header><div><span className="modal-index">DOCUMENT / 01</span><h2>문서 설정</h2></div><button onClick={onClose}>닫기</button></header>
    <div className="document-readout"><div><span>PHYSICAL</span><b>{width} × {height} mm</b></div><div><span>RASTER</span><b>{widthPx.toLocaleString()} × {heightPx.toLocaleString()} px</b></div><div className={pixels > 300_000_000 ? "danger" : ""}><span>EST. MEMORY</span><b>{memoryGb.toFixed(2)} GB</b></div></div>
    <div className="document-fields"><label><span>프리셋</span><select value="" onChange={(event) => { const preset = BOARD_PRESETS[Number(event.target.value)]; if (preset) { setWidth(preset.widthMm); setHeight(preset.heightMm); } }}><option value="">사용자 지정</option>{BOARD_PRESETS.map((preset, index) => <option key={preset.label} value={index}>{preset.label}</option>)}</select></label><label><span>비율 잠금</span><input type="checkbox" checked={lockRatio} onChange={(event) => setLockRatio(event.target.checked)} /></label><label><span>너비 mm</span><input type="number" value={width} onChange={(event) => setWidthSafe(Number(event.target.value))} /></label><label><span>높이 mm</span><input type="number" value={height} onChange={(event) => setHeightSafe(Number(event.target.value))} /></label><label><span>재단 mm</span><input type="number" value={bleed} step=".5" onChange={(event) => setBleed(Number(event.target.value))} /></label><label><span>안전 여백 mm</span><input type="number" value={safe} step=".5" onChange={(event) => setSafe(Number(event.target.value))} /></label><label><span>목표 DPI</span><input type="number" min="72" max="1200" value={dpi} onChange={(event) => setDpi(Number(event.target.value))} /></label><label><span>관람 거리 mm</span><input type="number" value={viewing} onChange={(event) => setViewing(Number(event.target.value))} /></label></div>
    <div className="resize-modes"><b>크기 변경 방식</b>{([['keep','요소의 실제 mm 유지'],['scale','요소와 글자 비례 조정'],['duplicate','원본 보존 후 새 보드 복제']] as const).map(([value,label]) => <label key={value} className={mode === value ? "active" : ""}><input type="radio" name="resize-mode" checked={mode === value} onChange={() => setMode(value)} /><span>{label}</span></label>)}</div>
    {pixels > 300_000_000 && <p className="safety-warning">3억 픽셀 안전 한도를 넘습니다. 편집은 가능하지만 래스터 출력 전에 크기 또는 DPI를 낮추세요.</p>}
    <div className="modal-actions"><button onClick={onClose}>취소</button><button className="primary" disabled={width <= 0 || height <= 0 || dpi < 72 || pixels > 300_000_000} onClick={apply}>변경 적용</button></div>
  </div></div>;
}

export function IntelligencePanel({ setNotice }: { setNotice: (value: string) => void }) {
  const state = useStudio(); const project = state.project!; const board = project.boards.find((item) => item.id === state.activeBoardId)!;
  const [section, setSection] = useState<"content" | "layout" | "references" | "presentation">(project.layoutProposals.length ? "layout" : "content"); const [busy, setBusy] = useState("");
  const [references, setReferences] = useState<ReferenceLayoutV1[]>([]); const [referenceUrl, setReferenceUrl] = useState(""); const refFile = useRef<HTMLInputElement>(null);
  useEffect(() => { void db.referenceLayouts.toArray().then(setReferences); }, []);
  const blocks = project.contentBlocks.filter((item) => item.boardId === board.id);
  const suggest = async () => { setBusy("labels"); try { const next = await suggestBlocks(project, board.id); state.commit((draft) => { draft.contentBlocks = draft.contentBlocks.filter((item) => item.boardId !== board.id); draft.contentBlocks.push(...next); }); setNotice(`${next.length}개 콘텐츠 블록을 제안했습니다. 원문은 변경하지 않았습니다.`); } catch (error) { setNotice(String(error)); } finally { setBusy(""); } };
  const selectedBlock = () => { if (!state.selectedIds.length) return; const id = newId(); state.commit((draft) => { draft.contentBlocks.push({ id, boardId: board.id, elementIds: [...state.selectedIds], label: "diagram", title: `콘텐츠 블록 ${blocks.length + 1}`, summary: "", readingOrder: blocks.length + 1, importance: 3, confidence: 1, status: "suggested", rationale: "사용자가 선택한 레이어로 직접 구성" }); }); };
  const makeReference = async (file?: File) => { if (!file) return; const form = new FormData(); form.append("file", file); const response = await fetch("/api/references/inspect", { method: "POST", body: form }); if (!response.ok) { setNotice("참고 레이아웃 파일을 검사하지 못했습니다."); return; } const ratio = 1; const item: ReferenceLayoutV1 = { id: newId(), provenance: { title: file.name, creator: "확인 필요", format: "확인 필요", sourceUrl: "local-file", license: "확인 필요", projectType: "architecture panel", collectedAt: new Date().toISOString() }, boardAspectRatio: ratio, columnCount: 3, whitespaceRatio: .2, blocks: [], featureVector: [ratio, .25, .2], approvalStatus: "review", createdAt: new Date().toISOString() }; await db.referenceLayouts.put(item); setReferences(await db.referenceLayouts.toArray()); };
  const inspectUrl = async () => { const response = await fetch("/api/references/inspect", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url: referenceUrl }) }); if (!response.ok) { setNotice((await response.json().catch(() => null))?.detail ?? "URL 검사 실패"); return; } const item: ReferenceLayoutV1 = { id: newId(), provenance: { title: new URL(referenceUrl).hostname, creator: "확인 필요", format: "확인 필요", sourceUrl: referenceUrl, license: "확인 필요", projectType: "architecture panel", collectedAt: new Date().toISOString() }, boardAspectRatio: 1, columnCount: 3, whitespaceRatio: .2, blocks: [], featureVector: [1,.25,.2], approvalStatus: "review", createdAt: new Date().toISOString() }; await db.referenceLayouts.put(item); setReferences(await db.referenceLayouts.toArray()); setReferenceUrl(""); };
  const updateReference = async (reference: ReferenceLayoutV1, field: "title" | "creator" | "format" | "license" | "projectType", value: string) => { reference.provenance[field] = value; await db.referenceLayouts.put(reference); setReferences(await db.referenceLayouts.toArray()); };
  return <div className="panel-scroll intelligence-panel">{project.id === "archipanel-decomposed-demo" && <div className="demo-flow-notice"><b>ATTACHED PANEL / DECOMPOSED</b><span>원본 1개 → 독립 crop 레이어 14개 → 승인 블록 14개 → 자동 추천 3안</span><small>원문을 새로 생성하거나 수정하지 않은 검증용 fixture입니다.</small></div>}<div className="flow-nav"><button className={section === "content" ? "active" : ""} onClick={() => setSection("content")}>01 라벨</button><button className={section === "layout" ? "active" : ""} onClick={() => setSection("layout")}>02 배치</button><button className={section === "references" ? "active" : ""} onClick={() => setSection("references")}>03 참고</button><button className={section === "presentation" ? "active" : ""} onClick={() => setSection("presentation")}>04 발표</button></div>
    {section === "content" && <><div className="smart-hero"><Sparkles size={20}/><div><b>콘텐츠 블록</b><span>제안 → 승인 → 확정 흐름</span></div></div><div className="smart-actions"><button className="primary" disabled={Boolean(busy)} onClick={() => void suggest()}><Sparkles size={14}/> 자동 제안</button><button disabled={!state.selectedIds.length} onClick={selectedBlock}><Plus size={14}/> 선택 묶기</button></div><div className="content-blocks">{blocks.map((block) => <article key={block.id} className={`content-block ${block.status}`}><div className="block-order">{String(block.readingOrder).padStart(2,'0')}</div><div><input value={block.title} onChange={(event) => state.commit((draft) => { const item=draft.contentBlocks.find((entry)=>entry.id===block.id); if(item)item.title=event.target.value; })}/><select value={block.label} onChange={(event) => state.commit((draft) => { const item=draft.contentBlocks.find((entry)=>entry.id===block.id); if(item)item.label=event.target.value as ContentLabel; })}>{CONTENT_LABELS.map((label)=><option key={label} value={label}>{LABEL_KO[label]??label}</option>)}</select><textarea placeholder="핵심 문장(원문 근거)" value={block.summary} onChange={(event)=>state.commit((draft)=>{const item=draft.contentBlocks.find((entry)=>entry.id===block.id);if(item)item.summary=event.target.value;})}/><small>{Math.round(block.confidence*100)}% · {block.rationale}</small><div className="block-actions"><button onClick={()=>state.setSelection(block.elementIds)}>원본 선택</button><button className={block.status === "approved" ? "approved" : ""} onClick={()=>state.commit((draft)=>{const item=draft.contentBlocks.find((entry)=>entry.id===block.id);if(item)item.status=item.status==="approved"?"suggested":"approved";})}><Check size={12}/> {block.status === "approved" ? "승인됨" : "승인"}</button></div></div></article>)}</div></>}
    {section === "layout" && <LayoutSection references={references} setNotice={setNotice}/>}
    {section === "references" && <><div className="smart-hero"><FileStack size={20}/><div><b>참고 레이아웃</b><span>출처가 승인된 구조 정보만 추천에 사용</span></div></div><div className="reference-import"><input value={referenceUrl} placeholder="https:// 직접 이미지/PDF URL" onChange={(event)=>setReferenceUrl(event.target.value)}/><button disabled={!referenceUrl} onClick={()=>void inspectUrl()}>URL 검사</button><button onClick={()=>refFile.current?.click()}><Upload size={13}/> 파일</button><input hidden ref={refFile} type="file" accept="image/png,image/jpeg,image/webp,application/pdf" onChange={(event)=>void makeReference(event.target.files?.[0])}/></div>{references.map((reference)=><article className="reference-row reference-edit" key={reference.id}><div><input aria-label="참고 제목" value={reference.provenance.title} onChange={(event)=>void updateReference(reference,"title",event.target.value)}/><input aria-label="제작자" value={reference.provenance.creator} onChange={(event)=>void updateReference(reference,"creator",event.target.value)}/><input aria-label="판형" value={reference.provenance.format} onChange={(event)=>void updateReference(reference,"format",event.target.value)}/><input aria-label="프로젝트 유형" value={reference.provenance.projectType} onChange={(event)=>void updateReference(reference,"projectType",event.target.value)}/><input aria-label="라이선스" value={reference.provenance.license} onChange={(event)=>void updateReference(reference,"license",event.target.value)}/><span>{reference.provenance.sourceUrl}</span><small>{new Date(reference.provenance.collectedAt).toLocaleDateString("ko-KR")} · {reference.columnCount}열</small></div><select value={reference.approvalStatus} onChange={async(event)=>{reference.approvalStatus=event.target.value as ReferenceLayoutV1['approvalStatus'];await db.referenceLayouts.put(reference);setReferences(await db.referenceLayouts.toArray());}}><option value="review">검토 전용</option><option value="approved">추천 승인</option><option value="rejected">제외</option></select></article>)}</>}
    {section === "presentation" && <PresentationSection setNotice={setNotice}/>}</div>;
}

function LayoutSection({ references, setNotice }: { references: ReferenceLayoutV1[]; setNotice: (value: string)=>void }) {
  const state=useStudio(); const project=state.project!; const boardId=state.activeBoardId!; const [proposals,setProposals]=useState<LayoutProposalV1[]>(project.layoutProposals.filter((item)=>item.boardId===boardId)); const [busy,setBusy]=useState(false);
  const run=async()=>{setBusy(true);try{const next=await recommendLayouts(project,boardId,references);state.commit((draft)=>{draft.layoutProposals=draft.layoutProposals.filter((item)=>item.boardId!==boardId);draft.layoutProposals.push(...next);});await db.recommendationRuns.put({id:newId(),projectId:project.id,boardId,createdAt:new Date().toISOString(),proposalIds:next.map((item)=>item.id)});setProposals(next);}catch(error){setNotice(error instanceof Error?error.message:String(error));}finally{setBusy(false);}};
  const apply=async(proposal:LayoutProposalV1)=>{const result=await validateProposal(project,proposal);if(!result.valid){setNotice(`배치 검증 실패: ${result.errors.join(', ')}`);return;}state.applyLayoutProposal(proposal);setNotice("추천안을 하나의 실행 취소 단계로 적용했습니다.");};
  return <><div className="smart-hero"><Grid3X3 size={20}/><div><b>세 가지 레이아웃</b><span>비율 유지 · 일정 gutter · 빈 공간 최소화</span></div></div><button className="primary full-action" disabled={busy||!project.contentBlocks.some((item)=>item.boardId===boardId&&item.status==="approved")} onClick={()=>void run()}>{busy?"계산 중…":"3안 생성"}</button><div className="proposal-list">{proposals.map((proposal)=><article className="proposal-card" key={proposal.id}><div className={`proposal-preview ${proposal.strategy}`}>{proposal.placements.slice(0,18).map((placement,index)=><i key={placement.elementId} style={{left:`${(placement.xMm/project.boards.find((b)=>b.id===boardId)!.widthMm)*100}%`,top:`${(placement.yMm/project.boards.find((b)=>b.id===boardId)!.heightMm)*100}%`,width:`${(placement.widthMm/project.boards.find((b)=>b.id===boardId)!.widthMm)*100}%`,height:`${(placement.heightMm/project.boards.find((b)=>b.id===boardId)!.heightMm)*100}%`,opacity:.35+(index%4)*.15}}/>)}</div><div><b>{proposal.strategy === "narrative"?"Narrative Grid":proposal.strategy==="hero"?"Hero Visual":"Technical Matrix"}</b><span>총점 {Math.round(Object.values(proposal.scoreBreakdown).reduce((a,b)=>a+b,0)/Object.values(proposal.scoreBreakdown).length)}</span>{proposal.packingMetrics&&<small className="packing-score">공간 {Math.round(proposal.packingMetrics.occupancy)}% · 행 정렬 {Math.round(proposal.packingMetrics.gridAlignment)}% · {proposal.packingMetrics.rowCount}행</small>}<small>{proposal.warnings.length?`${proposal.warnings.length}개 검토 경고`:"하드 제약 통과"}</small><button onClick={()=>void apply(proposal)}>이 안 적용</button></div></article>)}</div></>;
}

function PresentationSection({setNotice}:{setNotice:(value:string)=>void}){
  const state=useStudio();const project=state.project!;const [duration,setDuration]=useState(15);const [count,setCount]=useState(16);const [audience,setAudience]=useState("건축 설계 심사위원");const [spec,setSpec]=useState<StudioPresentationSpecV1|undefined>(project.presentationSpecs.at(-1));const [busy,setBusy]=useState(false);
  const generate=async()=>{setBusy(true);try{const next=await makeStoryboard(project,duration,count,audience);state.commit((draft)=>{draft.presentationSpecs.push(next);});await db.presentationSpecs.put(next);setSpec(next);}catch(error){setNotice(error instanceof Error?error.message:String(error));}finally{setBusy(false);}};
  const approve=()=>{if(!spec)return;const next={...spec,approvalStatus:"approved" as const,updatedAt:new Date().toISOString()};state.commit((draft)=>{const item=draft.presentationSpecs.find((entry)=>entry.id===next.id);if(item)Object.assign(item,next);});void db.presentationSpecs.put(next);setSpec(next);};
  const editSlide=(number:number,patch:Partial<StudioPresentationSpecV1["slides"][number]>)=>{if(!spec)return;const next={...spec,approvalStatus:"draft" as const,updatedAt:new Date().toISOString(),slides:spec.slides.map((slide)=>{if(slide.number!==number)return slide;const edited={...slide,...patch,...("keySentence" in patch&&String(patch.keySentence).trim()?{reviewFlags:[]}: {})};const sources=edited.sourceContentBlockIds.map((id)=>`- local-project://${project.id}/content-block/${id}`).join("\n");edited.speakerNotes=`발표 목적: ${edited.purpose}\n핵심 문장: ${edited.keySentence}\n예상 시간: ${edited.expectedSeconds}초\n설계 데이터 영역: ${edited.designSectionId}\n원본 블록: ${edited.sourceContentBlockIds.join(", ")}\n원본 요소: ${edited.sourceElementIds.join(", ")}\n검토 필요: ${edited.reviewFlags.join("; ")||"없음"}\n\n[Sources]\n${sources}\n[/Sources]`;return edited;})};setSpec(next);state.commit((draft)=>{const item=draft.presentationSpecs.find((entry)=>entry.id===next.id);if(item)Object.assign(item,next);});void db.presentationSpecs.put(next);};
  const exportPptx=async()=>{if(!spec||spec.approvalStatus!=="approved")return;setBusy(true);try{await downloadFromEndpoint(project,"/api/presentation/export-pptx",`${safeName(project.name)}-발표자료.pptx`,{presentationSpecId:spec.id});setNotice("편집 가능한 PPTX와 발표자 노트를 생성했습니다.");}catch(error){setNotice(error instanceof Error?error.message:String(error));}finally{setBusy(false);}};
  const total=useMemo(()=>spec?.slides.reduce((sum,slide)=>sum+slide.expectedSeconds,0)??0,[spec]);
  return <><div className="smart-hero"><Presentation size={20}/><div><b>설계설명 스토리보드</b><span>승인 근거 → 설계 데이터 → PPTX · 승인 전 출력 금지</span></div></div><div className="story-settings"><label>청중<input value={audience} onChange={(event)=>setAudience(event.target.value)}/></label><label>분<input type="number" min="3" max="60" value={duration} onChange={(event)=>setDuration(Number(event.target.value))}/></label><label>장<input type="number" min="3" max="60" value={count} onChange={(event)=>setCount(Number(event.target.value))}/></label></div><button className="primary full-action" disabled={busy} onClick={()=>void generate()}>{busy?"생성 중…":"설계설명서 생성"}</button>{spec&&<><div className="story-summary"><b>{spec.slideCount}장 · {Math.floor(total/60)}분 {total%60}초</b><span>{spec.slides.filter((slide)=>slide.reviewFlags.length).length}장 검토 필요</span></div>{spec.designExplanationData&&<div className="story-summary"><b>데이터 근거 {spec.designExplanationData.coverage.coveredSectionCount}/{spec.designExplanationData.coverage.totalSectionCount}</b><span>승인 블록 {spec.designExplanationData.coverage.approvedBlockCount}개 · 누락 {spec.designExplanationData.coverage.missingSectionIds.length}개</span></div>}<div className="story-table">{spec.slides.map((slide)=><article key={slide.number}><b>{String(slide.number).padStart(2,'0')}</b><input aria-label={`${slide.number}번 제목`} value={slide.title} onChange={(event)=>editSlide(slide.number,{title:event.target.value})}/><input aria-label={`${slide.number}번 시간`} type="number" value={slide.expectedSeconds} onChange={(event)=>editSlide(slide.number,{expectedSeconds:Number(event.target.value)})}/><textarea aria-label={`${slide.number}번 목적`} value={slide.purpose} onChange={(event)=>editSlide(slide.number,{purpose:event.target.value})}/><textarea aria-label={`${slide.number}번 핵심 문장`} value={slide.keySentence} onChange={(event)=>editSlide(slide.number,{keySentence:event.target.value})}/><small>{slide.designSectionId} · {slide.layoutKind} · BLOCK {slide.sourceContentBlockIds.join(" / ")} · ELEMENT {slide.sourceElementIds.join(" / ")}</small>{slide.reviewFlags.length>0&&<small className="readability-flags">검토: {slide.reviewFlags.join(" · ")}</small>}</article>)}</div><div className="story-actions"><button className={spec.approvalStatus==="approved"?"approved":""} disabled={total!==spec.durationMinutes*60} onClick={approve}><Check size={13}/> {spec.approvalStatus==="approved"?"승인됨":total!==spec.durationMinutes*60?"시간 합계 확인":"스토리보드 승인"}</button><button className="primary" disabled={spec.approvalStatus!=="approved"||busy} onClick={()=>void exportPptx()}>PPTX 내보내기</button></div></>}</>;
}

export function TypographyRoleControl({ elementId }: { elementId: string }) {
  const state=useStudio();const element=state.project?.elements.find((item)=>item.id===elementId);if(!element||element.type!=="text")return null;const warnings=readabilityWarnings(element,state.project?.boards.find((item)=>item.id===element.boardId)?.backgroundColor);
  return <><label><span>전역 역할</span><select value={element.styleRole} onChange={(event)=>state.commit((draft)=>{const target=draft.elements.find((item)=>item.id===element.id);if(target)applyTypographyRole(draft,target,event.target.value as TypographyRole);})}><option value="title">제목 64pt</option><option value="section">섹션 32pt</option><option value="body">본문 18pt</option><option value="caption">캡션 11pt</option></select></label>{warnings.length>0&&<div className="readability-flags">{warnings.map((warning)=><span key={warning}>{warning}</span>)}</div>}</>;
}
